// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **APP_ENV**  
   * The environment that this process runs against. It selects the `.env.<env>`  
   * files that varlock layers on top of this schema.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M7.885%2010.23L12%203.463l4.116%206.769zm9.606%2011q-1.558%200-2.64-1.081t-1.082-2.64t1.082-2.649t2.64-1.09t2.649%201.09t1.09%202.649t-1.09%202.64t-2.649%201.082m-13.722-.5v-6.462h6.462v6.462z%22%2F%3E%3C%2Fsvg%3E)  
   */
  APP_ENV: "development" | "test" | "staging" | "production"

  /**
   * **APP_URL**  
   * The absolute origin that serves the app. Better Auth uses it for OAuth redirect  
   * URIs and for signing absolute links. It has no default on purpose. Every  
   * environment inherits a default here, and a wrong OAuth callback host fails at  
   * the provider, not at boot. Development sets the portless URL in  
   * `.env.development`.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M24%2021V9h-2v14h8v-2zm-4-6v-4c0-1.103-.897-2-2-2h-6v14h2v-6h1.48l2.335%206h2.145l-2.333-6H18c1.103%200%202-.897%202-2m-6-4h4v4h-4zM8%2023H4c-1.103%200-2-.897-2-2V9h2v12h4V9h2v12c0%201.103-.897%202-2%202%22%2F%3E%3C%2Fsvg%3E)  
   */
  APP_URL: string

  /**
   * **DATABASE_URL** 🔐 _sensitive_  
   * The Postgres connection string. The default matches the credentials in  
   * `docker-compose.yml`. Those credentials are already in this repository in  
   * plaintext, so vaulting them adds ceremony without adding secrecy.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)  
   */
  DATABASE_URL: string

  /**
   * **BETTER_AUTH_SECRET** 🔐 _sensitive_  
   * These three items have no value in this file. Development reads them from  
   * `.env.local`, which is gitignored. Staging and production receive them as  
   * injected environment variables. `process.env` has the highest precedence. A  
   * missing value fails the load in those environments. The shared schema never  
   * names a vault item.  
   *
   * To read them from 1Password in development, put the references in your own  
   * `.env.local`:  
   *
   * BETTER_AUTH_SECRET=op(op://Acme/Local/better-auth-secret)  
   *
   * Signs session cookies and encrypts OAuth state.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)  
   */
  BETTER_AUTH_SECRET?: string

  /**
   * **GITHUB_CLIENT_ID**  
   * GitHub OAuth app credentials. The callback URL is  
   * `${APP_URL}/api/auth/callback/github`.  
   * The client id is not a secret. It is in the authorize URL that every browser  
   * visits, and Better Auth returns that URL in a response body. varlock's leak  
   * scanner aborts any response that contains a sensitive value. Leaving this item  
   * under `@defaultSensitive` therefore turns every sign-in into a 500. The secret  
   * below stays sensitive.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)  
   *
   * 📚 {@link https://github.com/settings/developers}  
   */
  GITHUB_CLIENT_ID?: string

  /**
   * **GITHUB_CLIENT_SECRET** 🔐 _sensitive_  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)  
   */
  GITHUB_CLIENT_SECRET?: string
}

type _CoercedEnvSchema_356ea601 = CoercedEnvSchema

export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]: NonNullable<CoercedEnvSchema[Property]> extends string
    ? NonNullable<CoercedEnvSchema[Property]>
    : NonNullable<CoercedEnvSchema[Property]> extends boolean
      ? "true" | "false"
      : string
}

type _EnvSchemaAsStrings_356ea601 = EnvSchemaAsStrings
